-- Create a Database
CREATE DATABASE IF NOT EXISTS CAMPAIGN;

-- Create a Schema
CREATE SCHEMA IF NOT EXISTS CAMPAIGN.THROWAWAYEMAIL;

--Create the customer identity table
CREATE TABLE IF NOT EXISTS CAMPAIGN.THROWAWAYEMAIL.CUSTOMER_IDENTITY (
EMAIL VARCHAR(255) NOT NULL,
HASHED_EMAIL VARCHAR(255) NOT NULL,
REGISTRATION_DATE DATETIME NOT NULL,
NAME VARCHAR(255) NOT NULL,
JOB_TITLE VARCHAR(255) NOT NULL,
INSTITUTION VARCHAR(255) NOT NULL
);

--Create the throwaway email results table
CREATE TABLE IF NOT EXISTS CAMPAIGN.THROWAWAYEMAIL.THROWAWAY_EMAIL_RESULTS (
EMAIL VARCHAR(255) NOT NULL,
HASHEDEMAIL VARCHAR(255) NOT NULL,
CHECKEDDATETIME DATETIME NOT NULL,
THROWAWAYSTATUS BOOLEAN NOT NULL
);